# Generated by Django 3.2.5 on 2021-11-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dresses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('size', models.CharField(max_length=30, verbose_name='Рост')),
                ('volume', models.PositiveIntegerField(verbose_name='Объем груди')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='dresses/media', verbose_name='Фото_1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='dresses/media', verbose_name='Фото_2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='dresses/media', verbose_name='Фото_3')),
            ],
            options={
                'verbose_name': ('Платье',),
                'verbose_name_plural': 'Платья',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('rent_date', models.DateTimeField(db_index=True, verbose_name='Дата брони')),
                ('type_lease', models.CharField(blank=True, max_length=50, null=True, verbose_name='Где будут использовать платье')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес доставки')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость заказа')),
                ('dress', models.ManyToManyField(related_name='orders', to='dresses.Dress', verbose_name='Платье')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': ('Заказ',),
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(blank=True, null=True, verbose_name='Дата аренды')),
                ('dress', models.ManyToManyField(related_name='baskets', to='dresses.Dress', verbose_name='Платье')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskets', to='sessions.session', verbose_name='Сессия')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
